### ISSUE TITLE
Question: Addition of custom labels in the roadmap?

### ISSUE THREAD

**Issue by kjhosein** [doitintl/iris3#13]
Hello,

Are you considering adding the ability to add custom labels to projects and/or resources?

e.g.: 
> environment = dev
> owner = "joe smith" 

etc.

Thanks!

**Comment by JoshuaFox** [comment]
How would Iris learn what the value of  'environment', or of 'owner', should be?

**Comment by kjhosein** [comment]
> How would Iris learn what the value of 'environment', or of 'owner', should be?

I was thinking from a user-supplied config file.

**Comment by JoshuaFox** [comment]
The preferred way to do this is to launch resources with Terraform and give labels at that time. Typically the CI/CD system is best positioned to have this information.

To do it in Iris, after launching resources, could you please give me a sample of such a config file? Here is one (pseudeocode)
```
- instance:
   indentifier: //compute.googleapis.com/projects/my-first-project/zones/us-west1/instances/my-first-instance
   label_name: environment
   label_value: billing-department
   label_name: owner
   label_value: John Smith
```

I am not sure that this makes sense. It would require manually building labels for potentially hundreds of resources, across many projects. Or do you prefer fancier logic in the config files, and if so, what? Some sort of usage of regular expressions?
